In [ ]:
import pandas as pd

### Note to Team: We are using Relative Paths. Place the dataset in the same folder as this notebook. If the file is missing, the script will automatically download it from the NYC Open Data link provided by Maryla.

In [ ]:
import pandas as pd
import os
import requests

# Variable Mapping
# This is the "CSV API" version of Maryla's query link
DATA_URL = "https://data.cityofnewyork.us/resource/erm2-nwe9.csv?$query=SELECT%20unique_key%2C%20created_date%2C%20closed_date%2C%20agency%2C%20agency_name%2C%20complaint_type%2C%20descriptor%2C%20location_type%2C%20incident_zip%2C%20incident_address%2C%20street_name%2C%20cross_street_1%2C%20cross_street_2%2C%20intersection_street_1%2C%20intersection_street_2%2C%20address_type%2C%20city%2C%20landmark%2C%20facility_type%2C%20status%2C%20due_date%2C%20resolution_description%2C%20resolution_action_updated_date%2C%20community_board%2C%20bbl%2C%20borough%2C%20x_coordinate_state_plane%2C%20y_coordinate_state_plane%2C%20open_data_channel_type%2C%20park_borough%2C%20latitude%2C%20longitude%2C%20location%20WHERE%20created_date%20BETWEEN%20%222024-01-01T00%3A00%3A00%22%20AND%20%222025-12-31T23%3A59%3A59%22%20AND%20agency%20!%3D%20%22HPD%22%20ORDER%20BY%20created_date%20DESC"

# This is the name the file will have on your computer
FILENAME = "311_Service_Requests_2024_2025.csv"

# Loading the data
if not os.path.exists(FILENAME):
    print(f"File '{FILENAME}' not found. Downloading directly from NYC Open Data...")
    # This downloads the file automatically so you don't have to change paths which is annoying. 
    r = requests.get(DATA_URL)
    with open(FILENAME, 'wb') as f:
        f.write(r.content)
    print("Download complete!")
else:
    print(f"File found locally. Loading from: {os.path.abspath(FILENAME)}")

# Added low_memory=False to stop the warning Maryla was getting in her notebook
df = pd.read_csv(FILENAME, on_bad_lines="skip", low_memory=False)

print(f"Success! Data loaded. Total rows: {len(df)}")

File found locally. Loading from: /Users/kenneth/Documents/School/Group_Project_311_Service_Requests/311_Service_Requests_2024_2025.csv

https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2020-to-Present/erm2-nwe9/explore/query/SELECT%0A%20%20%60unique_key%60%2C%0A%20%20%60created_date%60%2C%0A%20%20%60closed_date%60%2C%0A%20%20%60agency%60%2C%0A%20%20%60agency_name%60%2C%0A%20%20%60complaint_type%60%2C%0A%20%20%60descriptor%60%2C%0A%20%20%60location_type%60%2C%0A%20%20%60incident_zip%60%2C%0A%20%20%60incident_address%60%2C%0A%20%20%60street_name%60%2C%0A%20%20%60cross_street_1%60%2C%0A%20%20%60cross_street_2%60%2C%0A%20%20%60intersection_street_1%60%2C%0A%20%20%60intersection_street_2%60%2C%0A%20%20%60address_type%60%2C%0A%20%20%60city%60%2C%0A%20%20%60landmark%60%2C%0A%20%20%60facility_type%60%2C%0A%20%20%60status%60%2C%0A%20%20%60due_date%60%2C%0A%20%20%60resolution_description%60%2C%0A%20%20%60resolution_action_updated_date%60%2C%0A%20%20%60community_board%60%2C%0A%20%20%60bbl%60%2C%0A%20%20%60borough%60%2C%0A%20%20%60x_coordinate_state_plane%60%2C%0A%20%20%60y_coordinate_state_plane%60%2C%0A%20%20%60open_data_channel_type%60%2C%0A%20%20%60park_borough%60%2C%0A%20%20%60latitude%60%2C%0A%20%20%60longitude%60%2C%0A%20%20%60location%60%0AWHERE%0A%20%20%60created_date%60%0A%20%20%20%20BETWEEN%20%222024-01-01T16%3A23%3A16%22%20%3A%3A%20floating_timestamp%0A%20%20%20%20AND%20%222025-12-31T16%3A23%3A16%22%20%3A%3A%20floating_timestamp%0A%20%20AND%20caseless_ne%28%60agency%60%2C%20%22HPD%22%29%0AORDER%20BY%20%60created_date%60%20DESC%20NULL%20FIRST/page/filter


#### The downloaded data contains only 911 complaints for 2024 and 2025. File excludes HPD (New York City Department of Housing Preservation and Development) because it is usually concerned only with building conditions and is not relevant to our project conceptually.


**Data also does not include those columns:**
    "vehicle_type",
    "taxi_company_borough",
    "taxi_pick_up_location",
    "bridge_highway_name",
    "bridge_highway_direction",
    "road_ramp",
    "bridge_highway_segment",
    "due_date", 
    "resolution_description",
    "resolution_action_updated_date",
    "landmark",
    "facility_type"

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_state_plane,y_coordinate_state_plane,open_data_channel_type,park_borough,latitude,longitude,location
0,67351762,2025-12-31T23:59:28.000,2026-01-01T00:40:32.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10029.0,50 EAST 104 STREET,EAST 104 STREET,MADISON AVENUE,PARK AVENUE,MADISON AVENUE,PARK AVENUE,ADDRESS,NEW YORK,EAST 104 STREET,NaN,Closed,NaN,The New York City Police Department responded ...,2026-01-01T00:40:35.000,11 MANHATTAN,1.016080e+09,MANHATTAN,998068.0,227879.0,MOBILE,MANHATTAN,40.792141,-73.950097,POINT (-73.950097072847 40.792140506424)
1,67344624,2025-12-31T23:59:23.000,2026-01-01T01:03:42.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10031.0,549 WEST 144 STREET,WEST 144 STREET,AMSTERDAM AVENUE,BROADWAY,AMSTERDAM AVENUE,BROADWAY,ADDRESS,NEW YORK,WEST 144 STREET,NaN,Closed,NaN,The New York City Police Department responded ...,2026-01-01T01:03:44.000,09 MANHATTAN,1.020760e+09,MANHATTAN,998241.0,239901.0,ONLINE,MANHATTAN,40.825137,-73.949447,POINT (-73.949447237231 40.82513729001)
2,67346873,2025-12-31T23:59:21.000,2026-01-01T00:58:13.000,NYPD,New York City Police Department,Blocked Driveway,Partial Access,Street/Sidewalk,11234.0,1467 EAST 56 STREET,EAST 56 STREET,AVENUE M,AVENUE N,AVENUE M,AVENUE N,ADDRESS,BROOKLYN,EAST 56 STREET,NaN,Closed,NaN,The New York City Police Department responded ...,2026-01-01T00:58:18.000,18 BROOKLYN,3.078810e+09,BROOKLYN,1006135.0,165167.0,PHONE,BROOKLYN,40.619995,-73.921167,POINT (-73.921167390534 40.619994693785)
3,67353004,2025-12-31T23:59:20.000,2026-01-01T00:57:31.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11235.0,2416 EAST 14 STREET,EAST 14 STREET,AVENUE X,AVENUE Y,AVENUE X,AVENUE Y,ADDRESS,BROOKLYN,EAST 14 STREET,NaN,Closed,NaN,The New York City Police Department responded ...,2026-01-01T00:57:34.000,15 BROOKLYN,3.074150e+09,BROOKLYN,996476.0,154794.0,ONLINE,BROOKLYN,40.591542,-73.955979,POINT (-73.955979130812 40.591541524842)
4,67350526,2025-12-31T23:59:12.000,2026-01-01T00:41:16.000,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,10031.0,1635 AMSTERDAM AVENUE,AMSTERDAM AVENUE,WEST 140 STREET,WEST 141 STREET,WEST 140 STREET,WEST 141 STREET,ADDRESS,NEW YORK,AMSTERDAM AVENUE,NaN,Closed,NaN,The Police Department reviewed your complaint ...,2026-01-01T00:41:20.000,09 MANHATTAN,1.020570e+09,MANHATTAN,998220.0,238974.0,MOBILE,MANHATTAN,40.822593,-73.949525,POINT (-73.949525045155 40.822592971648)

In [9]:
df.columns

Index(['unique_key', 'created_date', 'closed_date', 'agency', 'agency_name',
       'complaint_type', 'descriptor', 'location_type', 'incident_zip',
       'incident_address', 'street_name', 'cross_street_1', 'cross_street_2',
       'intersection_street_1', 'intersection_street_2', 'address_type',
       'city', 'landmark', 'facility_type', 'status', 'due_date',
       'resolution_description', 'resolution_action_updated_date',
       'community_board', 'bbl', 'borough', 'x_coordinate_state_plane',
       'y_coordinate_state_plane', 'open_data_channel_type', 'park_borough',
       'latitude', 'longitude', 'location'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   unique_key                      1000 non-null   int64
 1   created_date                    1000 non-null   object
 2   closed_date                     989 non-null    object
 3   agency                          1000 non-null   object
 4   agency_name                     1000 non-null   object
 5   complaint_type                  1000 non-null   object
 6   descriptor                      963 non-null    object
 7   location_type                   936 non-null    object
 8   incident_zip                    994 non-null    float64
 9   incident_address                985 non-null    object
 10  street_name                     985 non-null    object
 11  cross_street_1                  961 non-null    object
 12  cross_street_2                  963 non-null    object
 13  intersection_street_1           936 non-null    object
 14  intersection_street_2           938 non-null    object
 15  address_type                    994 non-null    object
 16  city                            963 non-null    object
 17  landmark                        891 non-null    object
 18  facility_type                   3 non-null      object
 19  status                          1000 non-null   object
 20  due_date                        2 non-null      object
 21  resolution_description          991 non-null    object
 22  resolution_action_updated_date  991 non-null    object
 23  community_board                 1000 non-null   object
 24  bbl                             913 non-null    float64
 25  borough                         1000 non-null   object
 26  x_coordinate_state_plane        985 non-null    float64
 27  y_coordinate_state_plane        985 non-null    float64
 28  open_data_channel_type          1000 non-null   object
 29  park_borough                    1000 non-null   object
 30  latitude                        985 non-null    float64
 31  longitude                       985 non-null    float64
 32  location                        985 non-null    object
dtypes: float64(6), int64(1), object(26)
memory usage: 257.9+ KB

#### This part is added after Kenneth modifications 3.28.2026

### Since the data is now being pulled directly from the website, the column names differ from those used in the CSV extract. I will rename them here for consistency:

In [13]:
# original column names
cols_old = ['unique_key', 'created_date', 'closed_date', 'agency', 'agency_name',
            'complaint_type', 'descriptor', 'location_type', 'incident_zip',
            'incident_address', 'street_name', 'cross_street_1', 'cross_street_2',
            'intersection_street_1', 'intersection_street_2', 'address_type',
            'city', 'landmark', 'facility_type', 'status', 'due_date',
            'resolution_description', 'resolution_action_updated_date',
            'community_board', 'bbl', 'borough', 'x_coordinate_state_plane',
            'y_coordinate_state_plane', 'open_data_channel_type', 'park_borough',
            'latitude', 'longitude', 'location']

# target column names
cols_new = ['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
            'Problem (formerly Complaint Type)',
            'Problem Detail (formerly Descriptor)', 'Location Type', 'Incident Zip',
            'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
            'Intersection Street 1', 'Intersection Street 2', 'Address Type',
            'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
            'Resolution Description', 'Resolution Action Updated Date',
            'Community Board', 'BBL', 'Borough', 'X Coordinate (State Plane)',
            'Y Coordinate (State Plane)', 'Open Data Channel Type', 'Park Borough',
            'Latitude', 'Longitude', 'Location']

# build mapping
rename_dict = dict(zip(cols_old, cols_new))

# apply rename
df = df.rename(columns=rename_dict)

In [14]:
df.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Problem (formerly Complaint Type)',
       'Problem Detail (formerly Descriptor)', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Description', 'Resolution Action Updated Date',
       'Community Board', 'BBL', 'Borough', 'X Coordinate (State Plane)',
       'Y Coordinate (State Plane)', 'Open Data Channel Type', 'Park Borough',
       'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [15]:
df["Created Date"] = pd.to_datetime(
    df["Created Date"],
    format="%m/%d/%Y %I:%M:%S %p",
    errors="coerce"
)

df["Closed Date"] = pd.to_datetime(
    df["Created Date"],
    format="%m/%d/%Y %I:%M:%S %p",
    errors="coerce"
)

In [16]:
df["Complaint Year"] = df["Created Date"].dt.year

In [17]:
df["Complaint Month"] = df["Created Date"].dt.month

In [18]:
print(df["Complaint Year"].unique())
df["Complaint Month"].unique()

[nan]

array([nan])

In [19]:
df["Month Name"] = pd.to_datetime(df["Complaint Month"], format="%m").dt.month_name()

In [12]:
df["Month Name"].unique()

array([nan], dtype=object)

In [20]:
df["Agency"].unique()

array(['NYPD', 'TLC', 'DOB', 'DOT', 'DSNY', 'DCWP', 'DEP', 'DPR', 'EDC',
       'DOHMH', 'OOS'], dtype=object)

In [14]:
#df = df[df["agency"] != "HPD"]
#df["agency"].unique()

In [12]:
#df["Problem (formerly Complaint Type)"].unique()

In [21]:
#for the ease of use - we will rename the columns
df = df.rename(columns={
    "Problem (formerly Complaint Type)": "Complaint",
    "Problem Detail (formerly Descriptor)": "Complaint Detail"
})

In [22]:
df = df.rename(columns={
    'X Coordinate (State Plane)': "X Coordinate",
    'Y Coordinate (State Plane)': "Y Coordinate"
})

In [23]:
grouping_complaints = (
    df.groupby(["Agency", "Complaint","Complaint Detail"])
      .size()
      .reset_index(name="count")
)

In [24]:
grouping_complaints

,Agency,Complaint,Complaint Detail,count
0,DCWP,Consumer Complaint,Other Store (Non-Food),1
1,DCWP,Consumer Complaint,Restaurant,2
2,DEP,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",2
3,DEP,Asbestos,Asbestos Complaint (B1),1
4,DEP,Lead,Lead Kit Request (Residential) (L10),1
...,...,...,...,...
102,NYPD,Traffic,Drag Racing,3
103,OOS,Cannabis Retailer,Unlicensed,1
104,TLC,For Hire Vehicle Complaint,Driver Complaint - Passenger,1
105,TLC,Lost Property,Bag/Wallet,2
106,TLC,Taxi Complaint,Driver Complaint - Passenger,2

In [25]:
#if you want your own table :
# grouping_complaints.to_excel("complaints_by_agency_problem.xlsx", index=False)

In [26]:
df.isnull().sum()

Unique Key                           0
Created Date                      1000
Closed Date                       1000
Agency                               0
Agency Name                          0
Complaint                            0
Complaint Detail                    37
Location Type                       64
Incident Zip                         6
Incident Address                    15
Street Name                         15
Cross Street 1                      39
Cross Street 2                      37
Intersection Street 1               64
Intersection Street 2               62
Address Type                         6
City                                37
Landmark                           109
Facility Type                      997
Status                               0
Due Date                           998
Resolution Description               9
Resolution Action Updated Date       9
Community Board                      0
BBL                                 87
Borough                              0
X Coordinate                        15
Y Coordinate                        15
Open Data Channel Type               0
Park Borough                         0
Latitude                            15
Longitude                           15
Location                            15
Complaint Year                    1000
Complaint Month                   1000
Month Name                        1000
dtype: int64

We have 5,597,360 rows and for:
- 102,672 we do not have Location
- 102,639 we do not have X Coordinate
- 102,458 we do not have Y Coordinate

In [27]:
df[(df["Location"].notna()) & (df["X Coordinate"].isna())]

Empty DataFrame
Columns: [Unique Key, Created Date, Closed Date, Agency, Agency Name, Complaint, Complaint Detail, Location Type, Incident Zip, Incident Address, Street Name, Cross Street 1, Cross Street 2, Intersection Street 1, Intersection Street 2, Address Type, City, Landmark, Facility Type, Status, Due Date, Resolution Description, Resolution Action Updated Date, Community Board, BBL, Borough, X Coordinate, Y Coordinate, Open Data Channel Type, Park Borough, Latitude, Longitude, Location, Complaint Year, Complaint Month, Month Name]
Index: []

In [28]:
rows_with_location_missing_x = df[
    df["Location"].notna() & df["X Coordinate"].isna()
]

print("Number of rows:", len(rows_with_location_missing_x))  # should print 33
rows_with_location_missing_x.head()

Number of rows: 0

Empty DataFrame
Columns: [Unique Key, Created Date, Closed Date, Agency, Agency Name, Complaint, Complaint Detail, Location Type, Incident Zip, Incident Address, Street Name, Cross Street 1, Cross Street 2, Intersection Street 1, Intersection Street 2, Address Type, City, Landmark, Facility Type, Status, Due Date, Resolution Description, Resolution Action Updated Date, Community Board, BBL, Borough, X Coordinate, Y Coordinate, Open Data Channel Type, Park Borough, Latitude, Longitude, Location, Complaint Year, Complaint Month, Month Name]
Index: []

In [29]:
df[(df["Location"].notna()) & (df["Y Coordinate"].isna())]

Empty DataFrame
Columns: [Unique Key, Created Date, Closed Date, Agency, Agency Name, Complaint, Complaint Detail, Location Type, Incident Zip, Incident Address, Street Name, Cross Street 1, Cross Street 2, Intersection Street 1, Intersection Street 2, Address Type, City, Landmark, Facility Type, Status, Due Date, Resolution Description, Resolution Action Updated Date, Community Board, BBL, Borough, X Coordinate, Y Coordinate, Open Data Channel Type, Park Borough, Latitude, Longitude, Location, Complaint Year, Complaint Month, Month Name]
Index: []

In [30]:
df[["Location","X Coordinate"]].isna().value_counts()

Location  X Coordinate
False     False           985
True      True             15
Name: count, dtype: int64

5,494,689 rows → both Location and X Coordinate (State Plane) exist ✅

102,639 rows → Location is missing, X Coordinate is missing ❌

33 rows → X Coordinate exists but Location is missing ⚠

In [31]:
rows_with_location_missing_x = df[
    df["X Coordinate"].notna() & df["Location"].isna()
]

len(rows_with_location_missing_x)  # should print 33
rows_with_location_missing_x

Empty DataFrame
Columns: [Unique Key, Created Date, Closed Date, Agency, Agency Name, Complaint, Complaint Detail, Location Type, Incident Zip, Incident Address, Street Name, Cross Street 1, Cross Street 2, Intersection Street 1, Intersection Street 2, Address Type, City, Landmark, Facility Type, Status, Due Date, Resolution Description, Resolution Action Updated Date, Community Board, BBL, Borough, X Coordinate, Y Coordinate, Open Data Channel Type, Park Borough, Latitude, Longitude, Location, Complaint Year, Complaint Month, Month Name]
Index: []

We are removing all 33 where we do not have location and both Y and X coordinates

In [32]:
# Keep only rows where Location is not null
df = df[df["Location"].notna()]

# Quick check
df["Location"].isna().sum()  # should be 0

0

## We have some missing Compaint Detail, maybe we can replace the name of the Detaio wiht the compaint name

In [33]:
# Filter rows where Complaint Detail is null
missing_detail_rows = df[df["Complaint Detail"].isna()]

# Get unique Complaint values that have missing details
missing_complaints = missing_detail_rows["Complaint"].unique()

# Display them
missing_complaints

array(['Illegal Fireworks', 'Panhandling', 'Encampment'], dtype=object)

In [34]:
for complaint in missing_complaints:
    rows_with_details = df[(df["Complaint"] == complaint) & (df["Complaint Detail"].notna())]
    print(f"Complaint: {complaint}, Rows with details: {len(rows_with_details)}")
    display(rows_with_details.head())

Complaint: Illegal Fireworks, Rows with details: 0

Empty DataFrame
Columns: [Unique Key, Created Date, Closed Date, Agency, Agency Name, Complaint, Complaint Detail, Location Type, Incident Zip, Incident Address, Street Name, Cross Street 1, Cross Street 2, Intersection Street 1, Intersection Street 2, Address Type, City, Landmark, Facility Type, Status, Due Date, Resolution Description, Resolution Action Updated Date, Community Board, BBL, Borough, X Coordinate, Y Coordinate, Open Data Channel Type, Park Borough, Latitude, Longitude, Location, Complaint Year, Complaint Month, Month Name]
Index: []

Complaint: Panhandling, Rows with details: 0

Empty DataFrame
Columns: [Unique Key, Created Date, Closed Date, Agency, Agency Name, Complaint, Complaint Detail, Location Type, Incident Zip, Incident Address, Street Name, Cross Street 1, Cross Street 2, Intersection Street 1, Intersection Street 2, Address Type, City, Landmark, Facility Type, Status, Due Date, Resolution Description, Resolution Action Updated Date, Community Board, BBL, Borough, X Coordinate, Y Coordinate, Open Data Channel Type, Park Borough, Latitude, Longitude, Location, Complaint Year, Complaint Month, Month Name]
Index: []

Complaint: Encampment, Rows with details: 0

Empty DataFrame
Columns: [Unique Key, Created Date, Closed Date, Agency, Agency Name, Complaint, Complaint Detail, Location Type, Incident Zip, Incident Address, Street Name, Cross Street 1, Cross Street 2, Intersection Street 1, Intersection Street 2, Address Type, City, Landmark, Facility Type, Status, Due Date, Resolution Description, Resolution Action Updated Date, Community Board, BBL, Borough, X Coordinate, Y Coordinate, Open Data Channel Type, Park Borough, Latitude, Longitude, Location, Complaint Year, Complaint Month, Month Name]
Index: []

so it is almmost always miising detail fot those in a missing_complaints list, except for Asbestos, Illegal Fireworks, and Homeless Person Assistance

In [35]:
df[df["Complaint Detail"]=='Loud Music/Party']

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint,Complaint Detail,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Intersection Street 1,Intersection Street 2,Address Type,City,Landmark,Facility Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board,BBL,Borough,X Coordinate,Y Coordinate,Open Data Channel Type,Park Borough,Latitude,Longitude,Location,Complaint Year,Complaint Month,Month Name
0,67351762,NaT,NaT,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10029.0,50 EAST 104 STREET,EAST 104 STREET,MADISON AVENUE,PARK AVENUE,MADISON AVENUE,PARK AVENUE,ADDRESS,NEW YORK,EAST 104 STREET,NaN,Closed,NaN,The New York City Police Department responded ...,2026-01-01T00:40:35.000,11 MANHATTAN,1.016080e+09,MANHATTAN,998068.0,227879.0,MOBILE,MANHATTAN,40.792141,-73.950097,POINT (-73.950097072847 40.792140506424),NaN,NaN,NaN
1,67344624,NaT,NaT,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10031.0,549 WEST 144 STREET,WEST 144 STREET,AMSTERDAM AVENUE,BROADWAY,AMSTERDAM AVENUE,BROADWAY,ADDRESS,NEW YORK,WEST 144 STREET,NaN,Closed,NaN,The New York City Police Department responded ...,2026-01-01T01:03:44.000,09 MANHATTAN,1.020760e+09,MANHATTAN,998241.0,239901.0,ONLINE,MANHATTAN,40.825137,-73.949447,POINT (-73.949447237231 40.82513729001),NaN,NaN,NaN
3,67353004,NaT,NaT,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11235.0,2416 EAST 14 STREET,EAST 14 STREET,AVENUE X,AVENUE Y,AVENUE X,AVENUE Y,ADDRESS,BROOKLYN,EAST 14 STREET,NaN,Closed,NaN,The New York City Police Department responded ...,2026-01-01T00:57:34.000,15 BROOKLYN,3.074150e+09,BROOKLYN,996476.0,154794.0,ONLINE,BROOKLYN,40.591542,-73.955979,POINT (-73.955979130812 40.591541524842),NaN,NaN,NaN
4,67350526,NaT,NaT,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,10031.0,1635 AMSTERDAM AVENUE,AMSTERDAM AVENUE,WEST 140 STREET,WEST 141 STREET,WEST 140 STREET,WEST 141 STREET,ADDRESS,NEW YORK,AMSTERDAM AVENUE,NaN,Closed,NaN,The Police Department reviewed your complaint ...,2026-01-01T00:41:20.000,09 MANHATTAN,1.020570e+09,MANHATTAN,998220.0,238974.0,MOBILE,MANHATTAN,40.822593,-73.949525,POINT (-73.949525045155 40.822592971648),NaN,NaN,NaN
5,67349434,NaT,NaT,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11234.0,1760 UTICA AVENUE,UTICA AVENUE,AVENUE I,AVENUE J,AVENUE I,AVENUE J,ADDRESS,BROOKLYN,UTICA AVENUE,NaN,Closed,NaN,The New York City Police Department responded ...,2026-01-01T00:44:28.000,18 BROOKLYN,3.077750e+09,BROOKLYN,1004234.0,168582.0,ONLINE,BROOKLYN,40.629373,-73.928005,POINT (-73.928004925688 40.629372641946),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
947,67351841,NaT,NaT,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11417.0,137-20 CROSS BAY BOULEVARD,CROSS BAY BOULEVARD,VAN WICKLEN ROAD,149 AVENUE,VAN WICKLEN ROAD,149 AVENUE,ADDRESS,OZONE PARK,CROSS BAY BOULEVARD,NaN,Closed,NaN,The New York City Police Department responded ...,2025-12-31T21:54:23.000,10 QUEENS,4.114090e+09,QUEENS,1027800.0,183913.0,ONLINE,QUEENS,40.671368,-73.843006,POINT (-73.843006354489 40.671368329875),NaN,NaN,NaN
956,67349424,NaT,NaT,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10306.0,655 TYSENS LANE,TYSENS LANE,FALCON AVENUE,MILL ROAD,FALCON AVENUE,MILL ROAD,ADDRESS,STATEN ISLAND,TYSENS LANE,NaN,Closed,NaN,The New York City Police Department responded ...,2025-12-31T21:42:30.000,03 STATEN ISLAND,5.039830e+09,STATEN ISLAND,952579.0,144231.0,ONLINE,STATEN ISLAND,40.562500,-74.113985,POINT (-74.113984885689 40.562500040828),NaN,NaN,NaN
967,67345744,NaT,NaT,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,11249.0,97 WYTHE AVENUE,WYTHE AVENUE,NORTH 10 STREET,NORTH 9 STREET,NORTH 10 STREET,NORTH 9 STREET,ADDRESS,BROOKLYN,WYTHE AVENUE,NaN,Closed,NaN,The New York City Police Department responded ...,2025-12-31T21:37:54.000,01 BROOKLYN,3.023030e+09,BROOKLYN,995673.0,201973.0,MOBILE,BROOKLYN,40.721039,-73.958790,POINT (-73.958790492502 40.72103857354),NaN,NaN,NaN
990,67353603,NaT,NaT,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11433.0,108-12 157 STREET,157 STREET,108 AVENUE,109 AVENUE,108 AVENUE,109 AVENUE,ADDRESS,JAMAICA,157 STREET,NaN,Closed,NaN,The New York City Police Department responded ...,2026-01-01T05:35:47.000,12 QUEENS,NaN,QUEENS,1041031.0,192326.0,ONLINE,QUEENS,40.694385,-73.795239,POINT (-73.79523910737 40.694385062079),NaN,NaN,NaN
995,67352980,NaT,NaT,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10031.0,620 WEST 141 STREET,WEST 141 STREET,BROADWAY,RIVERSIDE DRIVE,BROADWAY,RIVERSIDE DRIVE,ADDRESS,NEW YORK,WEST 141 STREET,NaN,Closed,NaN,The New York City Police Department responded ...,2025-12-31T21:26:16.000,09 MANHATTAN,1.020880e+09,MANHATTAN,997264.0,239545.0,MOBILE,MANHATTAN,40.824162,-73.952978,POINT (-73.952978057044 40.824161664793),NaN,NaN,NaN

In [36]:
df[df["Complaint Detail"].str.contains("Fireworks", case=False, na=False)]

Empty DataFrame
Columns: [Unique Key, Created Date, Closed Date, Agency, Agency Name, Complaint, Complaint Detail, Location Type, Incident Zip, Incident Address, Street Name, Cross Street 1, Cross Street 2, Intersection Street 1, Intersection Street 2, Address Type, City, Landmark, Facility Type, Status, Due Date, Resolution Description, Resolution Action Updated Date, Community Board, BBL, Borough, X Coordinate, Y Coordinate, Open Data Channel Type, Park Borough, Latitude, Longitude, Location, Complaint Year, Complaint Month, Month Name]
Index: []

Some complaints don’t have a Complaint Detail because the complaint itself fully describes the issue. I will replace missing Complaint Detail values with the Complaint value.

In [37]:
df.loc[df["Complaint Detail"].isna(), "Complaint Detail"] = df["Complaint"]

In [38]:
df[df["Complaint Detail"].isna()]

Empty DataFrame
Columns: [Unique Key, Created Date, Closed Date, Agency, Agency Name, Complaint, Complaint Detail, Location Type, Incident Zip, Incident Address, Street Name, Cross Street 1, Cross Street 2, Intersection Street 1, Intersection Street 2, Address Type, City, Landmark, Facility Type, Status, Due Date, Resolution Description, Resolution Action Updated Date, Community Board, BBL, Borough, X Coordinate, Y Coordinate, Open Data Channel Type, Park Borough, Latitude, Longitude, Location, Complaint Year, Complaint Month, Month Name]
Index: []

## we also have null values in Closed Date

- Created Date    0
- Closed Date  136499

In [39]:
missing_closed_rows = df[df["Closed Date"].isna()]

# Get unique Complaint values for those rows
missing_closed_complaints = missing_closed_rows["Complaint"].unique()

# Display them
missing_closed_complaints

array(['Noise - Residential', 'Blocked Driveway', 'Noise - Commercial',
       'Illegal Parking', 'Illegal Fireworks', 'Noise - Street/Sidewalk',
       'Lost Property', 'Boilers', 'Street Light Condition',
       'Illegal Dumping', 'Elevator', 'Traffic Signal Condition',
       'Consumer Complaint', 'Noise - Vehicle', 'Water System',
       'Dead Animal', 'Panhandling', 'Animal-Abuse', 'Damaged Tree',
       'Encampment', 'General Construction/Plumbing',
       'For Hire Vehicle Complaint', 'Traffic', 'Street Condition',
       'Maintenance or Facility', 'Taxi Complaint', 'Noise',
       'Snow or Ice', 'Noise - Helicopter', 'Building/Use', 'Drinking',
       'Food Establishment', 'Indoor Sewage', 'Noise - House of Worship',
       'Dirty Condition', 'Smoking or Vaping', 'Sidewalk Condition',
       'Sewer', 'Indoor Air Quality', 'Abandoned Vehicle',
       'Non-Emergency Police Matter', 'Derelict Vehicles', 'Rodent',
       'Illegal Posting', 'Lead', 'Emergency Response Team (ERT)',
       'Residential Disposal Complaint', 'Mobile Food Vendor',
       'Drug Activity', 'Asbestos', 'Obstruction', 'Cannabis Retailer',
       'Air Quality', 'Graffiti', 'Water Quality',
       'Real Time Enforcement', 'Litter Basket Request', 'Food Poisoning',
       'Non-Residential Heat'], dtype=object)

I do not think it is relevan to our analysis so I will leave this as is

## Remove agencies that are not neighborhood-quality related

In [40]:
remove_agencies = [
    'TLC',     # taxi / ride complaints
    'DCWP',    # consumer complaints
    'OTI',     # LinkNYC / payphones
]

df = df[~df['Agency'].isin(remove_agencies)]

###  Remove complaint types that are not useful

In [41]:
remove_complaints = [
    'Lost Property',
    'Found Property',
    'Taxi Compliment',
    'Taxi Report',
    'For Hire Vehicle Report',
    'For Hire Vehicle Complaint',
    'Green Taxi Complaint',
    'Green Taxi Report',
    'Dispatched Taxi Complaint',
    'Taxi Licensee Complaint',
    'Public Payphone Complaint',
    'LinkNYC',
    'Consumer Complaint'
]

df = df[~df['Complaint'].isin(remove_complaints)]

### Remove vague / useless rows

In [42]:
df = df[~df['Complaint'].isin(['Unspecified'])]

### Remove information requests (not complaints)

In [43]:
remove_complaint_detail = [
    'Lead Kit Request (Residential) (L10)',
    'New Basket',
    'Replacement Basket',
    'New Bus Stop Shelter Placement'
]

df = df[~df['Complaint Detail'].isin(remove_complaint_detail)]

### Optional: Remove very rare complaint types ????

In [44]:
counts = df['Complaint'].value_counts()

df = df[df['Complaint'].isin(counts[counts > 100].index)]

In [45]:
df['Complaint'].value_counts().head(20)

Complaint
Noise - Residential    285
Illegal Parking        259
Blocked Driveway       115
Name: count, dtype: int64

In [46]:
df['Agency'].value_counts()

Agency
NYPD    659
Name: count, dtype: int64

the one left for a 311 is noise complaint - so we can leave it

### Create the mapping dictionary

In [47]:
category_map = {

# --------------------
# NOISE
# --------------------
"Noise - Residential": "Noise",
"Noise - Street/Sidewalk": "Noise",
"Noise - Commercial": "Noise",
"Noise - Vehicle": "Noise",
"Noise - Park": "Noise",
"Noise - Helicopter": "Noise",
"Noise": "Noise",

# --------------------
# PARKING & TRAFFIC
# --------------------
"Illegal Parking": "Parking & Traffic",
"Blocked Driveway": "Parking & Traffic",
"Traffic": "Parking & Traffic",

# --------------------
# SANITATION
# --------------------
"Dirty Condition": "Sanitation & Trash",
"Missed Collection": "Sanitation & Trash",
"Illegal Dumping": "Sanitation & Trash",
"Litter Basket Complaint": "Sanitation & Trash",
"Litter Basket Request": "Sanitation & Trash",
"Residential Disposal Complaint": "Sanitation & Trash",
"Commercial Disposal Complaint": "Sanitation & Trash",
"Dumpster Complaint": "Sanitation & Trash",
"Street Sweeping Complaint": "Sanitation & Trash",
"Obstruction": "Sanitation & Trash",
"Dead Animal": "Sanitation & Trash",

# --------------------
# RODENTS
# --------------------
"Rodent": "Rodents & Pests",

# --------------------
# STREET / INFRASTRUCTURE
# --------------------
"Street Condition": "Street & Infrastructure",
"Street Light Condition": "Street & Infrastructure",
"Sidewalk Condition": "Street & Infrastructure",
"Curb Condition": "Street & Infrastructure",
"Traffic Signal Condition": "Street & Infrastructure",
"Broken Parking Meter": "Street & Infrastructure",
"Street Sign - Damaged": "Street & Infrastructure",
"Street Sign - Missing": "Street & Infrastructure",
"Street Sign - Dangling": "Street & Infrastructure",
"Highway Condition": "Street & Infrastructure",
"Bridge Condition": "Street & Infrastructure",

# --------------------
# WATER / SEWER
# --------------------
"Water System": "Water & Sewer",
"Sewer": "Water & Sewer",
"Water Quality": "Water & Sewer",
"Water Conservation": "Water & Sewer",

# --------------------
# BUILDINGS
# --------------------
"Building/Use": "Buildings & Construction",
"General Construction/Plumbing": "Buildings & Construction",
"Construction Safety Enforcement": "Buildings & Construction",
"Elevator": "Buildings & Construction",
"Boilers": "Buildings & Construction",
"Electrical": "Buildings & Construction",
"Plumbing": "Buildings & Construction",
"Facade Insp Safety Pgm": "Buildings & Construction",

# --------------------
# PARKS / TREES
# --------------------
"Damaged Tree": "Parks & Trees",
"Dead/Dying Tree": "Parks & Trees",
"Overgrown Tree/Branches": "Parks & Trees",
"Illegal Tree Damage": "Parks & Trees",
"New Tree Request": "Parks & Trees",
"Root/Sewer/Sidewalk Condition": "Parks & Trees",
"Maintenance or Facility": "Parks & Trees",
"Violation of Park Rules": "Parks & Trees",
"Animal in a Park": "Parks & Trees",

# --------------------
# PUBLIC SAFETY
# --------------------
"Drug Activity": "Public Safety",
"Drinking": "Public Safety",
"Disorderly Youth": "Public Safety",
"Non-Emergency Police Matter": "Public Safety",
"Animal-Abuse": "Public Safety",

# --------------------
# ENVIRONMENT
# --------------------
"Air Quality": "Environment & Air Quality",
"Hazardous Materials": "Environment & Air Quality",
"Asbestos": "Environment & Air Quality"
}

In [48]:
#Apply the mapping
df["Main Complaint Category"] = df["Complaint"].map(category_map)

In [49]:
#Remove rows that did not map
df = df[df["Main Complaint Category"].notna()]

In [50]:
df["Main Complaint Category"].value_counts()

Main Complaint Category
Parking & Traffic    374
Noise                285
Name: count, dtype: int64

In [51]:
#sorted(df["Complaint"].unique())

## Remove additional columns to
- groupby operations faster
- visualizations easier
- code cleaner

In [52]:
df.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Complaint', 'Complaint Detail', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Description', 'Resolution Action Updated Date',
       'Community Board', 'BBL', 'Borough', 'X Coordinate', 'Y Coordinate',
       'Open Data Channel Type', 'Park Borough', 'Latitude', 'Longitude',
       'Location', 'Complaint Year', 'Complaint Month', 'Month Name',
       'Main Complaint Category'],
      dtype='object')

**we do not need those:**
BBL
X Coordinate
Y Coordinate
Location Type

Incident Address
Street Name
Cross Street 1
Cross Street 2
Intersection Street 1
Intersection Street 2
Address Type
Landmark
Location

**These describe how agencies processed the complaint: - remove as well**
Due Date
Resolution Description
Resolution Action Updated Date
Facility Type
Open Data Channel Type
Park Borough

for mapping we can keep:
    'Latitude', 'Longitude', 'Borough', 'Community Board'

In [53]:
drop_cols = [
'Incident Address','Street Name','Cross Street 1','Cross Street 2',
'Intersection Street 1','Intersection Street 2','Address Type',
'Landmark','Location',
'Due Date','Resolution Description','Resolution Action Updated Date',
'Facility Type','Open Data Channel Type','Park Borough',
'BBL','X Coordinate','Y Coordinate','Location Type','City'
]

df = df.drop(columns=drop_cols)

In [54]:
df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint,Complaint Detail,Incident Zip,Status,Community Board,Borough,Latitude,Longitude,Complaint Year,Complaint Month,Month Name,Main Complaint Category
0,67351762,NaT,NaT,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,10029.0,Closed,11 MANHATTAN,MANHATTAN,40.792141,-73.950097,NaN,NaN,NaN,Noise
1,67344624,NaT,NaT,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,10031.0,Closed,09 MANHATTAN,MANHATTAN,40.825137,-73.949447,NaN,NaN,NaN,Noise
2,67346873,NaT,NaT,NYPD,New York City Police Department,Blocked Driveway,Partial Access,11234.0,Closed,18 BROOKLYN,BROOKLYN,40.619995,-73.921167,NaN,NaN,NaN,Parking & Traffic
3,67353004,NaT,NaT,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,11235.0,Closed,15 BROOKLYN,BROOKLYN,40.591542,-73.955979,NaN,NaN,NaN,Noise
5,67349434,NaT,NaT,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,11234.0,Closed,18 BROOKLYN,BROOKLYN,40.629373,-73.928005,NaN,NaN,NaN,Noise

## need to fix zipcode - make it str

In [55]:
# Make sure Incident Zip is numeric (drop decimals) and then convert to string
df['Incident Zip'] = df['Incident Zip'].fillna(0).astype(int).astype(str)

# Optional: pad with leading zeros if needed (NYC zips are 5 digits)
df['Incident Zip'] = df['Incident Zip'].str.zfill(5)

## Lets see what we missing now

In [56]:
df.isnull().sum()

Unique Key                   0
Created Date               659
Closed Date                659
Agency                       0
Agency Name                  0
Complaint                    0
Complaint Detail             0
Incident Zip                 0
Status                       0
Community Board              0
Borough                      0
Latitude                     0
Longitude                    0
Complaint Year             659
Complaint Month            659
Month Name                 659
Main Complaint Category      0
dtype: int64

#### we just converted all zipcodes to str and missing one to 0 so need to chcek how many is still missing

In [57]:
missing_after = (df['Incident Zip'] == '00000').sum()
print("Missing/invalid ZIP codes after cleaning:", missing_after)

Missing/invalid ZIP codes after cleaning: 0

## save your cleaned dataset so we don’t have to repeat all the preprocessing

In [58]:
# Save your cleaned DataFrame to a CSV
df.to_csv("311_cleaned.csv", index=False)

# Optionally, save as a pickle for faster reloading with all dtypes preserved
df.to_pickle("311_cleaned.pkl")

## We have missing zipcodes

- Incident Zip   524 missing zipcodes

## --- KENNETH'S CHECKPOINT: PRODUCTION EXPORT ---
### Maryla's analysis above highlights the scale of the 5.6M row dataset.
### To ensure the Neighborhood Mapping and Dashboard run at peak performance,
### I am now exporting a cleaned version of the data.

In [59]:
# Columns Maryla identified for removal + rows without coordinates
drop_cols = [
    'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
    'Intersection Street 1', 'Intersection Street 2', 'Address Type',
    'Landmark', 'Location', 'Due Date', 'Resolution Description', 
    'Resolution Action Updated Date', 'Facility Type', 'Open Data Channel Type', 
    'Park Borough', 'BBL', 'X Coordinate (State Plane)', 'Y Coordinate (State Plane)', 
    'Location Type', 'City'
]

# Renamng the columns to the final project standard
df = df.rename(columns={
    "Problem (formerly Complaint Type)": "Complaint",
    "Problem Detail (formerly Descriptor)": "Complaint Detail"
})

# Creating the optimized dataframe
# Dropping the junk columns and remove rows with missing Lat/Long
df_final = df.drop(columns=drop_cols, errors='ignore').dropna(subset=['Latitude', 'Longitude'])

# Patching the missing Complaint Details with the main Category
df_final.loc[df_final["Complaint Detail"].isna(), "Complaint Detail"] = df_final["Complaint"]

# Making a shortcut to save memory
# Exporting this so we don't have to run the heavy loading/date conversion cells again
df_final.to_csv("311_Service_Requests_CLEANED.csv", index=False)

print(f"--- Production File Created ---")
print(f"Old Dataset Size: {len(df):,} rows")
print(f"New Optimized Size: {len(df_final):,} rows")

# Re-assigning df to the clean version so the Neighborhood Mapping below is lightning fast
df = df_final
del df_final # Freeing up RAM immediately so my computer runs faster

--- Production File Created ---
Old Dataset Size: 659 rows
New Optimized Size: 659 rows

## Mapping Neighborhoods & Fixing ZIP Codes

#### We have 524 missing ZIP codes and no neighborhood labels. Using the Latitude and Longitude coordinates, we will perform a spatial join with official NYC Shapefiles to:

#### Assign a Neighborhood (NTA) to every row so the HTML dashboard dropdown works.

#### Backfill missing ZIP codes where the data currently shows '00000'.

In [60]:
!pip install geopandas

Requirement already satisfied: geopandas in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (1.1.2)
Requirement already satisfied: numpy>=1.24 in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (from geopandas) (1.26.4)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (from geopandas) (23.0)
Requirement already satisfied: pandas>=2.0.0 in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (from pandas>=2.0.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (from pandas>=2.0.0->geopandas) (2024.2)
Requirement already satisfied: certifi in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2026.1.4)
Requirement already satisfied: six>=1.5 in c:\users\mw3595\appdata\local\anaconda3\jupyter\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.16.0)

In [61]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

# Loading the GeoJSON boundaries from the local files
nta_path = "2020_Neighborhood_Tabulation_Areas_(NTAs)_20260318.geojson"
zip_path = "Modified_Zip_Code_Tabulation_Areas_(MODZCTA)_20260318.geojson"

print("Loading local NYC Shapefiles...")
nta_gdf = gpd.read_file(nta_path)
zips_gdf = gpd.read_file(zip_path)

# Safety check for column names
if 'ntaname' in nta_gdf.columns:
    nta_gdf = nta_gdf.rename(columns={'ntaname': 'NTAName'})
if 'modzcta' in zips_gdf.columns:
    zips_gdf = zips_gdf.rename(columns={'modzcta': 'MODZCTA'})

# Preparing the 311 Data for Spatial Analysis
gdf_311 = gpd.GeoDataFrame(
    df, 
    geometry=gpd.points_from_xy(df.Longitude, df.Latitude),
    crs="EPSG:4326"
)

# Mapping to the Neighborhoods
print("Mapping coordinates to Neighborhood names...")
gdf_311 = gpd.sjoin(gdf_311, nta_gdf[['NTAName', 'geometry']], how="left", predicate="within")
gdf_311 = gdf_311.rename(columns={'NTAName': 'Neighborhood'})

# Dropping 'index_right' so the next join doesn't crash
if 'index_right' in gdf_311.columns:
    gdf_311 = gdf_311.drop(columns=['index_right'])

# Backfilling Missing ZIP Codes
missing_zip_mask = gdf_311['Incident Zip'].isin(['00000', '0', None, '', 'Unspecified'])
print(f"Backfilling {missing_zip_mask.sum()} missing ZIP codes using spatial join...")

# Only running the second join if there are actually missing ZIPs to find
if missing_zip_mask.any():
    zips_joined = gpd.sjoin(gdf_311[missing_zip_mask], zips_gdf[['MODZCTA', 'geometry']], how="left", predicate="within")
    
    # Updating the main 'Incident Zip' column
    gdf_311.loc[zips_joined.index, 'Incident Zip'] = zips_joined['MODZCTA']
    
    # Clean up index_right again after the second join
    if 'index_right' in gdf_311.columns:
        gdf_311 = gdf_311.drop(columns=['index_right'])

# Final Cleanup stuff
df = pd.DataFrame(gdf_311.drop(columns='geometry'))

print("\n--- Processing Complete ---")
print(f"Total Neighborhoods mapped: {df['Neighborhood'].notnull().sum()}")
print(f"Remaining '00000' ZIP codes: {(df['Incident Zip'] == '00000').sum()}")

# Saving the absolute final version
df.to_csv("NYC_311_Master_2024_2025.csv", index=False)
print("Master file saved! Ready for visualization.")

Loading local NYC Shapefiles...
Mapping coordinates to Neighborhood names...
Backfilling 0 missing ZIP codes using spatial join...

--- Processing Complete ---
Total Neighborhoods mapped: 659
Remaining '00000' ZIP codes: 0
Master file saved! Ready for visualization.

In [62]:
# A quick look at the top 10 neighborhoods
top_neighborhoods = df['Neighborhood'].value_counts().head(10)
print("--- TOP 10 NEIGHBORHOODS BY COMPLAINT VOLUME ---")
print(top_neighborhoods)

# Checking a few random rows to see the new Neighborhood column in action
df[['Complaint', 'Neighborhood', 'Incident Zip']].sample(5)

--- TOP 10 NEIGHBORHOODS BY COMPLAINT VOLUME ---
Neighborhood
Maspeth                     22
Jackson Heights             20
Crown Heights (South)       13
Woodhaven                   12
North Corona                10
East Village                10
Ocean Hill                  10
Williamsbridge-Olinville    10
Gravesend (West)            10
Glendale                     9
Name: count, dtype: int64

               Complaint                           Neighborhood Incident Zip
611      Illegal Parking                        Bushwick (East)        11207
486  Noise - Residential         Soundview-Bruckner-Bronx River        10472
657  Noise - Residential                  Bay Terrace-Clearview        11360
661  Noise - Residential                  Crown Heights (South)        11225
483      Illegal Parking  Flatbush (West)-Ditmas Park-Parkville        11218

In [ ]:
# Creating a 'Summary' file that is tiny but has all the chart data
df_summary = df.groupby(['Neighborhood', 'Complaint', 'Borough']).size().reset_index(name='Count')
df_summary.to_csv("NYC_311_Summary_Counts.csv", index=False)

In [1]:
import pandas as pd
import time
import os

# Instructions for the Team:
# 1. Ensure all CSV and GeoJSON files are in the same folder as this notebook.
# 2. Use 'df_summary' for 90% of our charts/visuals (it is fast).
# 3. Use 'df' ONLY for deep analysis requiring raw coordinates or timestamps.

# These are the relative paths. As long as these files are in your project folder, this code will work on any computer.
SUMMARY_FILE = "NYC_311_Summary_Counts.csv"
MASTER_FILE = "NYC_311_Master_2024_2025.csv"

print("Files Loaded:")
print("-" * 40)

# Loading the summary data
# Use df_summary for 90% of the charts, maps, and basic analysis.
if os.path.exists(SUMMARY_FILE):
    df_summary = pd.read_csv(SUMMARY_FILE)
    print(f"SUMMARY LOADED: Use 'df_summary' for quick charts and dashboarding.")
else:
    print(f"MISSING: {SUMMARY_FILE} not found. Run the cleaning cells above.")

# Loading the Master Data
# Use this df only if you need raw coordinates or specific timestamp details.
if os.path.exists(MASTER_FILE):
    print(f"LOADING MASTER FILE: This is ~1.1GB...")
    start_time = time.time()
    
    # Loading the file
    df = pd.read_csv(MASTER_FILE, low_memory=False)
    
    elapsed = round(time.time() - start_time, 2)
    print(f"MASTER LOADED: Use 'df' for deep analysis. (Load time: {elapsed}s)")
else:
    print(f"MISSING: {MASTER_FILE} not found.")

print("-" * 40)
print("The files are ready.")

Files Loaded:
----------------------------------------
SUMMARY LOADED: Use 'df_summary' for quick charts and dashboarding.
LOADING MASTER FILE: This is ~1.1GB...
ASTER LOADED: Use 'df' for deep analysis. (Load time: 15.25s)
----------------------------------------
The files are ready.